<?php

namespace AndersonAv\Firebird\Schema;

use Illuminate\Database\Schema\Blueprint as BaseBlueprint;
use Illuminate\Support\Fluent;

class Blueprint extends BaseBlueprint
{
    /**
     * Add an auto-incrementing ID column (Firebird).
     *
     * @param string $column
     * @return \Illuminate\Support\Fluent
     */
    public function id($column = 'ID'): Fluent
    {
        // Firebird: INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        return $this->integer($column)->primary()->autoIncrement();
    }

    /**
     * Add a string (VARCHAR) column in uppercase (Firebird convention).
     *
     * @param string $column
     * @param int $length
     * @return \Illuminate\Support\Fluent
     */
    public function string($column, $length = 255): Fluent
    {
        return parent::string(strtoupper($column), $length);
    }

    /**
     * Add created_at and updated_at columns in uppercase (Firebird convention).
     *
     * @param int $precision
     * @return void
     */
    public function timestamps($precision = 0)
    {
        $this->timestamp('CREATED_AT', $precision)->nullable();
        $this->timestamp('UPDATED_AT', $precision)->nullable();
    }

    /**
     * Add a remember token column in uppercase (Firebird convention).
     *
     * @return \Illuminate\Support\Fluent
     */
    public function rememberToken(): Fluent
    {
        return $this->string('REMEMBER_TOKEN', 100)->nullable();
    }

    // Você pode sobrescrever outros métodos conforme precisar, sempre usando strtoupper
}
